DROP TABLE IF EXISTS effect;

CREATE TABLE IF NOT EXISTS effect (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME_ESP TEXT NOT NULL,
    NAME_ENG TEXT NOT NULL,
    DESCRIPTION_ESP TEXT NOT NULL,
    DESCRIPTION_ENG TEXT NOT NULL,
    EFFECT TEXT
);

DROP TABLE IF EXISTS item;

CREATE TABLE IF NOT EXISTS item (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ICON INTEGER NOT NULL,
    NAME_ESP TEXT NOT NULL,
    NAME_ENG TEXT NOT NULL,
    DESCRIPTION_ESP TEXT NOT NULL,
    DESCRIPTION_ENG TEXT NOT NULL,
    EFFECT INTEGER,
    AMOUNT INTEGER,
    FOREIGN KEY (EFFECT) REFERENCES effect (ID) ON UPDATE CASCADE ON DELETE CASCADE
);

DROP TABLE IF EXISTS event;

CREATE TABLE IF NOT EXISTS event (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    DESCRIPTION_ESP TEXT NOT NULL,
    DESCRIPTION_ENG TEXT NOT NULL,
    EFFECT INTEGER,
    AMOUNT INTEGER,
    FOREIGN KEY (EFFECT) REFERENCES effect (ID) ON UPDATE CASCADE ON DELETE CASCADE
);

DROP TABLE IF EXISTS place;

CREATE TABLE IF NOT EXISTS place (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ICON INTEGER NOT NULL,
    PLACETYPE TEXT NOT NULL CHECK (
        PLACETYPE IN (
            'AU_HOUSE',
            'ANTENNA',
            'CONSTRUCTION',
            'FOREST',
            'LONELY',
            'SHELTER',
            'RUINS',
            'STILLNESS',
            'TOMB',
            'TOWN',
            'PLANT',
            'WELL'
        )
    ),
    NAME_ESP TEXT NOT NULL,
    NAME_ENG TEXT NOT NULL,
    DESCRIPTION_ESP TEXT NOT NULL,
    DESCRIPTION_ENG TEXT NOT NULL,
    -- OPTION 1 (CAN BE NULL)--
    OPTION1_ESP TEXT,
    OPTION1_ENG TEXT,
    ANSWER1_ESP TEXT,
    ANSWER1_ENG TEXT,
    ITEM1 INTEGER,
    EFFECT1 INTEGER,
    -- OPTION 2 (CAN BE NULL)--
    OPTION2_ESP TEXT,
    OPTION2_ENG TEXT,
    ANSWER2_ESP TEXT,
    ANSWER2_ENG TEXT,
    ITEM2 INTEGER,
    EFFECT2 INTEGER,
    -- OPTION 3 (CAN BE NULL)--
    OPTION3_ESP TEXT,
    OPTION3_ENG TEXT,
    ANSWER3_ESP TEXT,
    ANSWER3_ENG TEXT,
    ITEM3 INTEGER,
    EFFECT3 INTEGER,
    -- FK --
    FOREIGN KEY (ITEM1) REFERENCES item (ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (ITEM2) REFERENCES item (ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (ITEM3) REFERENCES item (ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (EFFECT1) REFERENCES effect (ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (EFFECT2) REFERENCES effect (ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (EFFECT3) REFERENCES effect (ID) ON UPDATE CASCADE ON DELETE CASCADE
);